### ISSUE TITLE
[Issue] The spot lights don't light the character. Only Directional light does.

### ISSUE THREAD

**Issue by rvv27** [Broxxar/PixelArtPipeline#1]
After downloading the repository the issue can be replicated by directly loading the pixel animation scene and putting Spot lights in front of the character. Changing the rotation of Directional light affects the light on character But the Spot light has no effect on the character.

I tried changing Unity versions but the same issue happens in all cases Unity 2018.1,2018.2,2018.3
Will be glad if you may assist.

**Comment by Broxxar** [comment]
Correct, in the video, only directional lighting was written. Options for supporting point and spot lights were outside the scope of the video. One option is to create a `ForwardAdd` light pass to handle the other types of lights. Unity defines macros for which type of light is being evaluated. Check out the `AutoLight.cginc` file in Unity's built in shaders for examples.

You can also access up to 8 lights a Vertex lit path. Don't let the name fool you, the uniform variables are still bound for use in fragment programs (of course at an increased performance cost).

Then there's also the bleeding-edge stuff in SRP. You could write your own RenderPipeline or extend LWRP to support your ideal pixel lighting.

Because this repo/video was about the pipeline and an example of lighting in 2D with normals, adding support for more lighting features is not really appropriate (and as illustrated by the options, there isn't a one-size-fits-all solution to implement).

You're welcome to make a PR with some examples of more advanced lighting support for this technique (though I would refrain from editing the shaders included in the project because they need to be accurate to what was showcased in the video).
